# Generated by Django 6.0 on 2025-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_name', models.CharField(max_length=50, verbose_name='观众姓名')),
                ('audience_id_card', models.CharField(blank=True, max_length=30, null=True, verbose_name='证件号')),
                ('seat_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='座位号')),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='票价')),
                ('purchase_channel', models.CharField(choices=[('大湾区线上', '大湾区线上'), ('大湾区线下', '大湾区线下'), ('其他', '其他')], max_length=10, verbose_name='购票渠道')),
                ('refund_status', models.CharField(choices=[('未退票', '未退票'), ('已退票', '已退票')], default='未退票', max_length=5, verbose_name='退票状态')),
                ('entry_verification_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='核验码')),
                ('notice_confirm_status', models.CharField(choices=[('已确认', '已确认'), ('未确认', '未确认')], default='未确认', max_length=5, verbose_name='观赛须知确认')),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name='入场时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '观众票务',
                'verbose_name_plural': '观众票务',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=100, verbose_name='赞助商名称')),
                ('sponsor_type', models.CharField(choices=[('现金', '现金'), ('物资', '物资'), ('服务', '服务')], max_length=10, verbose_name='赞助类型')),
                ('sponsor_value', models.CharField(max_length=100, verbose_name='赞助金额/物资')),
                ('coop_period', models.CharField(blank=True, max_length=50, null=True, verbose_name='合作期限')),
                ('bay_register_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='大湾区注册地址')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '赞助商',
                'verbose_name_plural': '赞助商',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SponsorRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights_type', models.CharField(choices=[('冠名', '冠名'), ('广告', '广告'), ('颁奖', '颁奖'), ('物料赞助', '物料赞助')], max_length=10, verbose_name='权益类型')),
                ('rights_status', models.CharField(choices=[('已执行', '已执行'), ('未执行', '未执行'), ('部分执行', '部分执行')], default='未执行', max_length=10, verbose_name='执行状态')),
                ('exposure_count', models.PositiveIntegerField(default=0, verbose_name='曝光次数')),
                ('bay_media_channel', models.CharField(blank=True, max_length=255, null=True, verbose_name='媒体渠道')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '赞助商权益',
                'verbose_name_plural': '赞助商权益',
                'ordering': ['-create_time'],
            },
        ),
    ]
