# Generated by Django 6.0 on 2025-12-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('event_management', '0001_initial'),
        ('finance_safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audienceticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='audience_tickets', to='event_management.event', verbose_name='项目'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['sponsor_type'], name='idx_sponsor_type'),
        ),
        migrations.AddField(
            model_name='sponsorrights',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_rights', to='event_management.event', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='sponsorrights',
            name='finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_rights', to='finance_safety.finance', verbose_name='财务结算'),
        ),
        migrations.AddField(
            model_name='sponsorrights',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='business.sponsor', verbose_name='赞助商'),
        ),
        migrations.AddIndex(
            model_name='audienceticket',
            index=models.Index(fields=['event'], name='idx_ticket_event'),
        ),
        migrations.AddIndex(
            model_name='audienceticket',
            index=models.Index(fields=['audience_id_card'], name='idx_ticket_idcard'),
        ),
        migrations.AddIndex(
            model_name='sponsorrights',
            index=models.Index(fields=['sponsor'], name='idx_rights_sponsor'),
        ),
        migrations.AddIndex(
            model_name='sponsorrights',
            index=models.Index(fields=['event'], name='idx_rights_event'),
        ),
    ]
