# Generated by Django 6.0 on 2025-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_dimension', models.CharField(max_length=50, verbose_name='统计维度')),
                ('stat_indicator', models.CharField(max_length=100, verbose_name='统计指标')),
                ('report_type', models.CharField(choices=[('日报', '日报'), ('周报', '周报'), ('总榜', '总榜'), ('专项', '专项')], max_length=10, verbose_name='报表类型')),
                ('stat_data', models.TextField(verbose_name='统计数据JSON')),
                ('generate_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('export_status', models.CharField(choices=[('已导出', '已导出'), ('未导出', '未导出')], default='未导出', max_length=5, verbose_name='导出状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据统计报表',
                'verbose_name_plural': '数据统计报表',
                'ordering': ['-generate_time'],
                'indexes': [models.Index(fields=['stat_dimension'], name='idx_report_dimension'), models.Index(fields=['report_type'], name='idx_report_type'), models.Index(fields=['generate_time'], name='idx_report_generate')],
            },
        ),
    ]
