# Generated by Django 6.0 on 2025-12-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealArbitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbitration_time', models.DateTimeField(blank=True, null=True, verbose_name='仲裁时间')),
                ('arbitration_basis', models.TextField(blank=True, null=True, verbose_name='仲裁依据')),
                ('arbitration_result', models.TextField(verbose_name='仲裁结果')),
                ('public_time', models.DateTimeField(blank=True, null=True, verbose_name='公示时间')),
                ('bay_arb_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='仲裁条例引用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '申诉仲裁',
                'verbose_name_plural': '申诉仲裁',
                'ordering': ['-arbitration_time', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrationCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(max_length=100, verbose_name='委员会名称')),
                ('member_ids', models.TextField(blank=True, null=True, verbose_name='成员ID列表')),
                ('scope', models.CharField(blank=True, max_length=255, null=True, verbose_name='职责范围')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系方式')),
                ('arbitration_process_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='仲裁流程文档')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仲裁委员会',
                'verbose_name_plural': '仲裁委员会',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_content', models.TextField(verbose_name='申诉内容')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('status', models.CharField(choices=[('待处理', '待处理'), ('已受理', '已受理'), ('已驳回', '已驳回'), ('已解决', '已解决')], default='待处理', max_length=5, verbose_name='处理状态')),
                ('result', models.TextField(blank=True, null=True, verbose_name='处理结果')),
                ('handler_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='处理人编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='basic_info.athlete', verbose_name='运动员')),
            ],
            options={
                'verbose_name': '申诉',
                'verbose_name_plural': '申诉',
                'ordering': ['-submit_time'],
            },
        ),
    ]
