# Generated by Django 6.0 on 2025-12-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appeal_arbitration', '0001_initial'),
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='event_management.event', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='appealarbitration',
            name='appeal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbitration', to='appeal_arbitration.appeal', verbose_name='申诉'),
        ),
        migrations.AddField(
            model_name='appealarbitration',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='arbitrations', to='appeal_arbitration.arbitrationcommittee', verbose_name='仲裁委员会'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['athlete'], name='idx_appeal_athlete'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['event'], name='idx_appeal_event'),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['status'], name='idx_appeal_status'),
        ),
        migrations.AddIndex(
            model_name='appealarbitration',
            index=models.Index(fields=['committee'], name='idx_arbitration_committee'),
        ),
    ]
