# Generated by Django 6.0 on 2025-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpidemicSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('运动员', '运动员'), ('观众', '观众'), ('工作人员', '工作人员')], max_length=10, verbose_name='人员类型')),
                ('person_id', models.PositiveIntegerField(verbose_name='人员ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体温')),
                ('safety_training_status', models.CharField(choices=[('已培训', '已培训'), ('未培训', '未培训')], default='未培训', max_length=10, verbose_name='安全培训状态')),
                ('emergency_record', models.TextField(blank=True, null=True, verbose_name='应急记录')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '防疫安全',
                'verbose_name_plural': '防疫安全',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['person_type', 'person_id'], name='idx_es_person')],
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_type', models.CharField(choices=[('报名费', '报名费'), ('赞助费', '赞助费'), ('后勤费', '后勤费'), ('奖金', '奖金'), ('其他', '其他')], max_length=10, verbose_name='收支类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('related_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联单号')),
                ('payer_payee', models.CharField(blank=True, max_length=100, null=True, verbose_name='付款/收款方')),
                ('settle_status', models.CharField(choices=[('已结算', '已结算'), ('未结算', '未结算')], default='未结算', max_length=10, verbose_name='结算状态')),
                ('bay_tax_record_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='税务备案号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '财务结算',
                'verbose_name_plural': '财务结算',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['finance_type'], name='idx_finance_type'), models.Index(fields=['related_no'], name='idx_finance_related')],
            },
        ),
    ]
