# Generated by Django 6.0 on 2025-12-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='代表队名称')),
                ('region', models.CharField(max_length=50, verbose_name='所属大湾区城市')),
                ('city_code', models.CharField(max_length=6, verbose_name='城市编码')),
                ('leader_name', models.CharField(max_length=50, verbose_name='领队姓名')),
                ('leader_phone', models.CharField(max_length=20, verbose_name='领队电话')),
                ('doctor_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='队医姓名')),
                ('doctor_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='队医电话')),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='队徽地址')),
                ('accommodation', models.CharField(blank=True, max_length=255, null=True, verbose_name='住宿信息')),
                ('transport', models.CharField(blank=True, max_length=255, null=True, verbose_name='交通安排')),
                ('uniform_custom', models.CharField(blank=True, max_length=255, null=True, verbose_name='队服定制信息')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='经费预算')),
                ('insurance_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='保险单号')),
                ('physical_report_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='体检报告地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代表队',
                'verbose_name_plural': '代表队',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['region'], name='idx_team_region'), models.Index(fields=['city_code'], name='idx_team_city_code')],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('其他', '其他')], max_length=2, verbose_name='性别')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('id_card', models.CharField(blank=True, max_length=30, null=True, verbose_name='证件号')),
                ('bay_area_hukou', models.CharField(choices=[('广东', '广东'), ('香港', '香港'), ('澳门', '澳门'), ('其他', '其他')], max_length=10, verbose_name='大湾区户籍')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='身高米')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体重公斤')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急联系电话')),
                ('health_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='健康状况')),
                ('qualification_status', models.CharField(choices=[('已审核', '已审核'), ('未审核', '未审核'), ('驳回', '驳回')], default='未审核', max_length=10, verbose_name='资格状态')),
                ('competition_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='参赛证号')),
                ('past_records', models.TextField(blank=True, null=True, verbose_name='过往参赛记录')),
                ('doping_test', models.CharField(choices=[('合格', '合格'), ('不合格', '不合格'), ('待检测', '待检测')], default='待检测', max_length=10, verbose_name='兴奋剂检测')),
                ('clothing_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='服装尺码')),
                ('insurance_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='保险信息')),
                ('join_time', models.DateTimeField(blank=True, null=True, verbose_name='入队时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='basic_info.team', verbose_name='所属代表队')),
            ],
            options={
                'verbose_name': '运动员',
                'verbose_name_plural': '运动员',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['team'], name='idx_athlete_team'), models.Index(fields=['bay_area_hukou'], name='idx_athlete_hukou'), models.Index(fields=['qualification_status'], name='idx_athlete_qual')],
            },
        ),
    ]
