# Generated by Django 6.0 on 2025-12-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('event_type', models.CharField(max_length=50, verbose_name='项目类型')),
                ('gender_limit', models.CharField(choices=[('男', '男'), ('女', '女'), ('混合', '混合')], max_length=2, verbose_name='性别限制')),
                ('player_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='参赛人数限制')),
                ('event_time', models.DateTimeField(blank=True, null=True, verbose_name='比赛时间')),
                ('rule_doc_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='规则文档')),
                ('apply_deadline', models.DateTimeField(blank=True, null=True, verbose_name='报名截止时间')),
                ('bay_feature', models.CharField(choices=[('是', '是'), ('否', '否')], default='否', max_length=2, verbose_name='湾区特色项目')),
                ('score_rule', models.TextField(blank=True, null=True, verbose_name='积分规则')),
                ('live_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='直播地址')),
                ('equipment_list', models.TextField(blank=True, null=True, verbose_name='器材清单')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '比赛项目',
                'verbose_name_plural': '比赛项目',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('age_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='年龄范围')),
                ('rule', models.TextField(blank=True, null=True, verbose_name='分组规则')),
                ('disability_integration', models.CharField(choices=[('是', '是'), ('否', '否')], default='否', max_length=2, verbose_name='残健融合')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '赛事分组',
                'verbose_name_plural': '赛事分组',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100, verbose_name='场地名称')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='容纳人数')),
                ('address', models.CharField(max_length=255, verbose_name='场地地址')),
                ('facility_status', models.CharField(choices=[('正常', '正常'), ('维修中', '维修中'), ('停用', '停用')], default='正常', max_length=10, verbose_name='设施状态')),
                ('manager_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='负责人')),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='负责人电话')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '比赛场地',
                'verbose_name_plural': '比赛场地',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='AthleteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('apply_status', models.CharField(choices=[('已报名', '已报名'), ('已取消', '已取消'), ('审核中', '审核中')], default='审核中', max_length=10, verbose_name='报名状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_events', to='basic_info.athlete', verbose_name='运动员')),
            ],
            options={
                'verbose_name': '运动员报名',
                'verbose_name_plural': '运动员报名',
                'ordering': ['-apply_time'],
            },
        ),
    ]
