# Generated by Django 6.0 on 2025-12-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_management', '0001_initial'),
        ('referee_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='referee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='referee_management.refereegroup', verbose_name='裁判组'),
        ),
        migrations.AddField(
            model_name='athleteevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_events', to='event_management.event', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='group',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='event_management.event', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='athleteevent',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_events', to='event_management.group', verbose_name='分组'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['venue_name'], name='idx_venue_name'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='event_management.venue', verbose_name='场地'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['event'], name='idx_group_event'),
        ),
        migrations.AddIndex(
            model_name='athleteevent',
            index=models.Index(fields=['athlete'], name='idx_ae_athlete'),
        ),
        migrations.AddIndex(
            model_name='athleteevent',
            index=models.Index(fields=['event'], name='idx_ae_event'),
        ),
        migrations.AlterUniqueTogether(
            name='athleteevent',
            unique_together={('athlete', 'event', 'group')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='idx_event_type'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue'], name='idx_event_venue'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['bay_feature'], name='idx_event_bay_feature'),
        ),
    ]
