# Generated by Django 6.0 on 2025-12-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='裁判姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('其他', '其他')], max_length=2, verbose_name='性别')),
                ('referee_level', models.CharField(choices=[('国家级', '国家级'), ('省级', '省级'), ('大湾区认证', '大湾区认证')], max_length=20, verbose_name='裁判等级')),
                ('charge_event', models.CharField(blank=True, max_length=100, null=True, verbose_name='负责项目')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('bay_cert', models.CharField(choices=[('有', '有'), ('无', '无')], default='无', max_length=5, verbose_name='湾区认证')),
                ('multi_language', models.CharField(blank=True, max_length=50, null=True, verbose_name='多语言能力')),
                ('referee_history', models.TextField(blank=True, null=True, verbose_name='执裁历史')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '裁判',
                'verbose_name_plural': '裁判',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['referee_level'], name='idx_referee_level'), models.Index(fields=['bay_cert'], name='idx_referee_cert')],
            },
        ),
        migrations.CreateModel(
            name='RefereeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='裁判组名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_groups', to='event_management.event', verbose_name='负责项目')),
                ('leader_referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_groups', to='referee_management.referee', verbose_name='组长')),
            ],
            options={
                'verbose_name': '裁判组',
                'verbose_name_plural': '裁判组',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='RefereeArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrange_date', models.DateTimeField(verbose_name='执裁时间')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='执裁岗位')),
                ('check_in_status', models.CharField(choices=[('已签到', '已签到'), ('未签到', '未签到')], default='未签到', max_length=5, verbose_name='签到状态')),
                ('evaluation', models.CharField(blank=True, max_length=255, null=True, verbose_name='执裁评价')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_arrangements', to='event_management.event', verbose_name='项目')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='referee_management.referee', verbose_name='裁判')),
                ('referee_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='referee_management.refereegroup', verbose_name='裁判组')),
            ],
            options={
                'verbose_name': '执裁安排',
                'verbose_name_plural': '执裁安排',
                'ordering': ['-arrange_date'],
            },
        ),
        migrations.AddIndex(
            model_name='refereegroup',
            index=models.Index(fields=['event'], name='idx_ref_group_event'),
        ),
        migrations.AddIndex(
            model_name='refereearrangement',
            index=models.Index(fields=['referee'], name='idx_arr_referee'),
        ),
        migrations.AddIndex(
            model_name='refereearrangement',
            index=models.Index(fields=['event'], name='idx_arr_event'),
        ),
    ]
