# Generated by Django 6.0 on 2025-12-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('service_type', models.CharField(max_length=50, verbose_name='服务类型')),
                ('bay_register_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='大湾区注册地址')),
                ('qualification_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='资质证书地址')),
                ('coop_period', models.CharField(blank=True, max_length=50, null=True, verbose_name='合作期限')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('performance_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='履约评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['service_type'], name='idx_supplier_service_type')],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('其他', '其他')], max_length=2, verbose_name='性别')),
                ('bay_school_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='大湾区院校/单位')),
                ('service_post', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务岗位')),
                ('service_time_slot', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务时段')),
                ('training_status', models.CharField(choices=[('已培训', '已培训'), ('未培训', '未培训')], default='未培训', max_length=10, verbose_name='培训状态')),
                ('working_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='服务工时')),
                ('evaluation', models.CharField(blank=True, max_length=255, null=True, verbose_name='服务评价')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '志愿者',
                'verbose_name_plural': '志愿者',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['service_post'], name='idx_vol_service_post'), models.Index(fields=['training_status'], name='idx_vol_training')],
            },
        ),
        migrations.CreateModel(
            name='LogisticsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('餐饮', '餐饮'), ('住宿', '住宿'), ('医疗', '医疗'), ('交通', '交通'), ('器材', '器材')], max_length=10, verbose_name='保障类型')),
                ('service_object_type', models.CharField(choices=[('运动员', '运动员'), ('裁判', '裁判'), ('工作人员', '工作人员')], max_length=10, verbose_name='服务对象类型')),
                ('service_object_id', models.PositiveIntegerField(verbose_name='服务对象ID')),
                ('service_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务单号')),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用金额')),
                ('service_time', models.DateTimeField(blank=True, null=True, verbose_name='服务时间')),
                ('staff_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务人员')),
                ('satisfaction_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='满意度评分')),
                ('exception_record', models.TextField(blank=True, null=True, verbose_name='异常记录')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics', to='logistics.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '后勤保障明细',
                'verbose_name_plural': '后勤保障明细',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['service_object_type', 'service_object_id'], name='idx_logistics_object'), models.Index(fields=['supplier'], name='idx_logistics_supplier')],
            },
        ),
    ]
