# Generated by Django 6.0 on 2025-12-05 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_link', models.CharField(choices=[('报名', '报名'), ('检录', '检录'), ('比赛', '比赛'), ('颁奖', '颁奖'), ('申诉', '申诉')], max_length=10, verbose_name='运营环节')),
                ('status', models.CharField(choices=[('未开始', '未开始'), ('进行中', '进行中'), ('已结束', '已结束')], default='未开始', max_length=5, verbose_name='状态')),
                ('staff_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='负责人编号')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('exception_log', models.TextField(blank=True, null=True, verbose_name='异常日志')),
                ('bay_approval_status', models.CharField(choices=[('已审批', '已审批'), ('未审批', '未审批')], default='未审批', max_length=5, verbose_name='湾区审批状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='event_management.event', verbose_name='项目')),
            ],
            options={
                'verbose_name': '赛事运营',
                'verbose_name_plural': '赛事运营',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['event'], name='idx_op_event'), models.Index(fields=['operation_link'], name='idx_op_link')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='日程日期')),
                ('time_slot', models.CharField(max_length=50, verbose_name='时间段')),
                ('status', models.CharField(choices=[('未开始', '未开始'), ('进行中', '进行中'), ('已结束', '已结束')], default='未开始', max_length=5, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='event_management.event', verbose_name='项目')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='schedules', to='event_management.venue', verbose_name='场地')),
            ],
            options={
                'verbose_name': '赛事日程',
                'verbose_name_plural': '赛事日程',
                'ordering': ['-schedule_date', '-time_slot'],
                'indexes': [models.Index(fields=['event'], name='idx_schedule_event'), models.Index(fields=['venue'], name='idx_schedule_venue'), models.Index(fields=['schedule_date'], name='idx_schedule_date')],
            },
        ),
    ]
